### ISSUE TITLE
安装出错了

### ISSUE THREAD

**Issue by luweimy** [kgrossjo/atom-svn-status#1]
在Atom编辑器中手动安装，重启出错，提示找不到什么东西

**Comment by Arcanemagus** [comment]
Going off the Google Translate of: "Manual installation, restart error in Atom editor, not able to find anything"

It sounds like you are seeing an error on startup of Atom, can you post the trace or a screenshot?

**Comment by kgrossjo** [comment]
Thank you @Arcanemagus .  Yes.  We need more information.

@Luweimy could you please provide more detail to explain what happens?

**Comment by kgrossjo** [comment]
Never mind.  I see now.  `atom-svn` uses `space-pen-views` which is deprecated.  Not sure quite yet what the replacement is, though.

**Comment by kgrossjo** [comment]
After 1e5e1992ffbd95ad4bdc7eee65a14d7eb9bb752e it's a bit better now, but still it is not working right.  I'm not sure how to proceed from here.

Is it okay to close this issue and to open another one that explains the next action?

**Comment by kgrossjo** [comment]
I have discovered another Atom package at https://github.com/andischerer/atom-svn/ and so I renamed this github repo and this package to "atom-svn-status".

**Comment by kgrossjo** [comment]
I've opened issue #2 for the "next action" that I mentioned some hours ago.  Meanwhile, I was able to close issue #2.  Of course, there is still more to do.  I will close this issue now and proceed with a new ticket for the next action.
